packages:
  - 'frontend/apps/*'
  - 'frontend/packages/*'
  - 'backend/apps/*'
  - 'backend/services/*'
  - 'contracts/*'
  - 'packages/*'
  - 'apps/*'
  - 'domains/*'
  - 'services/*'
  - 'workers/*'
allowBuilds:
  '@google/genai': set this to true or false
  esbuild: true
  protobufjs: set this to true or false
