packages:
  - 'frontend/apps/*'
  - 'frontend/packages/*'
  - 'backend/apps/*'
  - 'backend/services/*'
  - 'contracts/*'
  - 'packages/*'
  - 'apps/*'
  - 'domains/*'
  - 'services/*'
  - 'workers/*'
allowBuilds:
  esbuild: true
