/**
 * ShiVi Agent Runtime — 38 Specialized Core Agents Roster
 * Standard: Master Operating Prompt Phase 5
 */

import { RiskLevel } from '@shivi/kernel';

export interface SpecializedAgentSpec {
  agentId: string;
  name: string;
  category: 'GTM' | 'REVOPS' | 'KNOWLEDGE' | 'GOVERNANCE' | 'HARNESS' | 'OPS';
  description: string;
  version: string;
  riskLevel: RiskLevel;
  allowedTools: string[];
  memoryScope: 'WORKING' | 'TASK' | 'ACCOUNT' | 'ORGANIZATION';
  defaultModel: string;
  timeoutMs: number;
  retryPolicy: { maxRetries: number; backoffMultiplier: number };
  approvalRequired: boolean;
  evaluationThreshold: number;
}

export const SHIVI_38_CORE_AGENTS: SpecializedAgentSpec[] = [
  {
    agentId: 'orchestrator-agent',
    name: 'Master Orchestrator Agent',
    category: 'OPS',
    description: 'Decomposes complex B2B RevOps goals, coordinates specialized subagents, and synthesizes multi-turn execution trajectories.',
    version: '1.0.0',
    riskLevel: 'T2',
    allowedTools: ['dispatch_subagent', 'read_memory', 'write_memory', 'audit_log'],
    memoryScope: 'ORGANIZATION',
    defaultModel: 'gemini-1.5-pro',
    timeoutMs: 60000,
    retryPolicy: { maxRetries: 3, backoffMultiplier: 2.0 },
    approvalRequired: false,
    evaluationThreshold: 90,
  },
  {
    agentId: 'executive-intelligence-agent',
    name: 'Executive Intelligence Agent',
    category: 'GTM',
    description: 'Generates C-suite briefings, analyzes board-level ARR risks, and provides macro pipeline intelligence.',
    version: '1.0.0',
    riskLevel: 'T1',
    allowedTools: ['query_forecast', 'query_pipeline', 'synthesize_brief'],
    memoryScope: 'ORGANIZATION',
    defaultModel: 'gemini-1.5-pro',
    timeoutMs: 30000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 92,
  },
  {
    agentId: 'research-agent',
    name: 'Market & Account Research Agent',
    category: 'GTM',
    description: 'Performs deep web, SEC filing, and firmographic research on target accounts.',
    version: '1.0.0',
    riskLevel: 'T1',
    allowedTools: ['web_search', 'read_url', 'extract_sec_filing'],
    memoryScope: 'ACCOUNT',
    defaultModel: 'claude-3-5-sonnet',
    timeoutMs: 45000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 2.0 },
    approvalRequired: false,
    evaluationThreshold: 88,
  },
  {
    agentId: 'account-intelligence-agent',
    name: 'Account 360 Intelligence Agent',
    category: 'GTM',
    description: 'Constructs unified 360-degree account profiles from CRM history, product telemetry, and support tickets.',
    version: '1.0.0',
    riskLevel: 'T1',
    allowedTools: ['read_crm_account', 'read_telemetry', 'read_tickets'],
    memoryScope: 'ACCOUNT',
    defaultModel: 'gemini-1.5-pro',
    timeoutMs: 30000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 90,
  },
  {
    agentId: 'icp-agent',
    name: 'Ideal Customer Profile (ICP) Agent',
    category: 'GTM',
    description: 'Scores account and lead fit against dynamic Ideal Customer Profile rubrics and assigns strategic tiers.',
    version: '1.0.0',
    riskLevel: 'T1',
    allowedTools: ['evaluate_icp_score', 'read_rubric'],
    memoryScope: 'ORGANIZATION',
    defaultModel: 'gemini-1.5-flash',
    timeoutMs: 15000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 85,
  },
  {
    agentId: 'enrichment-agent',
    name: 'Data Enrichment Agent',
    category: 'GTM',
    description: 'Enriches lead and contact records with tech stack, headcount, and verified work email data.',
    version: '1.0.0',
    riskLevel: 'T1',
    allowedTools: ['enrich_contact', 'enrich_company', 'verify_email'],
    memoryScope: 'TASK',
    defaultModel: 'gemini-1.5-flash',
    timeoutMs: 20000,
    retryPolicy: { maxRetries: 3, backoffMultiplier: 2.0 },
    approvalRequired: false,
    evaluationThreshold: 88,
  },
  {
    agentId: 'lead-qualification-agent',
    name: 'Lead Qualification Agent',
    category: 'GTM',
    description: 'Applies MEDDPICC and BANT qualification frameworks to inbound and outbound leads.',
    version: '1.0.0',
    riskLevel: 'T1',
    allowedTools: ['score_meddpicc', 'score_bant', 'update_lead_qualification'],
    memoryScope: 'ACCOUNT',
    defaultModel: 'claude-3-5-sonnet',
    timeoutMs: 25000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 90,
  },
  {
    agentId: 'lead-routing-agent',
    name: 'Lead Routing Agent',
    category: 'GTM',
    description: 'Routes qualified leads to appropriate account executives based on territory, industry, and rep capacity.',
    version: '1.0.0',
    riskLevel: 'T2',
    allowedTools: ['lookup_territory', 'check_rep_capacity', 'assign_lead'],
    memoryScope: 'ORGANIZATION',
    defaultModel: 'gemini-1.5-flash',
    timeoutMs: 15000,
    retryPolicy: { maxRetries: 3, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 95,
  },
  {
    agentId: 'sdr-agent',
    name: 'Autonomous SDR Agent',
    category: 'GTM',
    description: 'Orchestrates multi-channel prospecting cadences, identifies net-new accounts, and crafts personalized angles.',
    version: '1.0.0',
    riskLevel: 'T2',
    allowedTools: ['create_outreach_campaign', 'schedule_sequence', 'search_leads'],
    memoryScope: 'ACCOUNT',
    defaultModel: 'gemini-1.5-pro',
    timeoutMs: 30000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 88,
  },
  {
    agentId: 'outreach-agent',
    name: 'Personalized Outreach Agent',
    category: 'GTM',
    description: 'Generates context-aware, hyper-relevant outbound emails and LinkedIn messages using company signals.',
    version: '1.0.0',
    riskLevel: 'T2',
    allowedTools: ['draft_email', 'generate_social_dm'],
    memoryScope: 'TASK',
    defaultModel: 'claude-3-5-sonnet',
    timeoutMs: 20000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 90,
  },
  {
    agentId: 'meeting-intelligence-agent',
    name: 'Meeting Intelligence Agent',
    category: 'GTM',
    description: 'Parses meeting recordings, extracts stakeholder sentiment, action items, objections, and next steps.',
    version: '1.0.0',
    riskLevel: 'T1',
    allowedTools: ['transcribe_audio', 'extract_action_items', 'analyze_sentiment'],
    memoryScope: 'ACCOUNT',
    defaultModel: 'gemini-1.5-pro',
    timeoutMs: 45000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 92,
  },
  {
    agentId: 'buying-committee-agent',
    name: 'Buying Committee Mapping Agent',
    category: 'REVOPS',
    description: 'Maps key decision makers (Champion, Economic Buyer, Technical Evaluator, Legal/Procurement, Blockers).',
    version: '1.0.0',
    riskLevel: 'T2',
    allowedTools: ['map_stakeholder_graph', 'detect_missing_buyer', 'read_crm_contacts'],
    memoryScope: 'ACCOUNT',
    defaultModel: 'gemini-1.5-pro',
    timeoutMs: 30000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 94,
  },
  {
    agentId: 'deal-strategy-agent',
    name: 'Deal Strategy & Positioning Agent',
    category: 'REVOPS',
    description: 'Synthesizes competitive battlecards, next-best-actions, and pricing concession strategies.',
    version: '1.0.0',
    riskLevel: 'T2',
    allowedTools: ['query_battlecard', 'recommend_concession', 'generate_proposal'],
    memoryScope: 'ACCOUNT',
    defaultModel: 'claude-3-5-sonnet',
    timeoutMs: 35000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 90,
  },
  {
    agentId: 'deal-risk-agent',
    name: 'Deal Risk & Slippage Agent',
    category: 'REVOPS',
    description: 'Detects stalled deal velocities, silent stakeholders, competitor presence, and forecast slippage indicators.',
    version: '1.0.0',
    riskLevel: 'T2',
    allowedTools: ['calculate_deal_velocity', 'detect_stalled_stage', 'alert_deal_risk'],
    memoryScope: 'ACCOUNT',
    defaultModel: 'gemini-1.5-pro',
    timeoutMs: 25000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 95,
  },
  {
    agentId: 'pipeline-intelligence-agent',
    name: 'Pipeline Intelligence Agent',
    category: 'REVOPS',
    description: 'Analyzes stage-by-stage funnel conversion, pipeline coverage ratios, and cohort aging.',
    version: '1.0.0',
    riskLevel: 'T1',
    allowedTools: ['compute_pipeline_coverage', 'analyze_conversion_rates'],
    memoryScope: 'ORGANIZATION',
    defaultModel: 'gemini-1.5-pro',
    timeoutMs: 30000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 90,
  },
  {
    agentId: 'forecast-agent',
    name: 'Revenue Forecasting Agent',
    category: 'REVOPS',
    description: 'Calculates probabilistic weighted ARR/MRR forecasts, confidence intervals, and scenario models.',
    version: '1.0.0',
    riskLevel: 'T2',
    allowedTools: ['calculate_weighted_forecast', 'generate_forecast_snapshot'],
    memoryScope: 'ORGANIZATION',
    defaultModel: 'gemini-1.5-pro',
    timeoutMs: 30000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 95,
  },
  {
    agentId: 'territory-agent',
    name: 'Territory & Quota Planning Agent',
    category: 'REVOPS',
    description: 'Optimizes sales territory boundaries, TAM balance, and sales rep quota allocations.',
    version: '1.0.0',
    riskLevel: 'T2',
    allowedTools: ['model_territory_split', 'calculate_quota_attainment'],
    memoryScope: 'ORGANIZATION',
    defaultModel: 'gemini-1.5-flash',
    timeoutMs: 25000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 88,
  },
  {
    agentId: 'renewal-agent',
    name: 'Contract Renewal Agent',
    category: 'REVOPS',
    description: 'Monitors 90/60/30-day renewal countdowns, contractual terms, and early renewal playbooks.',
    version: '1.0.0',
    riskLevel: 'T2',
    allowedTools: ['track_renewal_timeline', 'draft_renewal_proposal'],
    memoryScope: 'ACCOUNT',
    defaultModel: 'claude-3-5-sonnet',
    timeoutMs: 25000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 92,
  },
  {
    agentId: 'expansion-agent',
    name: 'Account Expansion & Upsell Agent',
    category: 'REVOPS',
    description: 'Identifies product seat consumption surges, cross-sell opportunities, and expansion playbooks.',
    version: '1.0.0',
    riskLevel: 'T2',
    allowedTools: ['detect_expansion_signal', 'recommend_upsell_package'],
    memoryScope: 'ACCOUNT',
    defaultModel: 'gemini-1.5-pro',
    timeoutMs: 25000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 90,
  },
  {
    agentId: 'customer-health-agent',
    name: 'Customer Health Scoring Agent',
    category: 'REVOPS',
    description: 'Aggregates usage telemetry, support tickets, and sentiment into a unified 0–100 health index.',
    version: '1.0.0',
    riskLevel: 'T1',
    allowedTools: ['compute_health_score', 'detect_churn_risk'],
    memoryScope: 'ACCOUNT',
    defaultModel: 'gemini-1.5-flash',
    timeoutMs: 20000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 90,
  },
  {
    agentId: 'customer-success-agent',
    name: 'Customer Success Copilot',
    category: 'OPS',
    description: 'Assists CSMs with quarterly business reviews (QBRs), customer outreach, and onboarding milestones.',
    version: '1.0.0',
    riskLevel: 'T2',
    allowedTools: ['generate_qbr_deck', 'schedule_csm_touchpoint'],
    memoryScope: 'ACCOUNT',
    defaultModel: 'claude-3-5-sonnet',
    timeoutMs: 30000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 90,
  },
  {
    agentId: 'onboarding-agent',
    name: 'Customer Onboarding Agent',
    category: 'OPS',
    description: 'Tracks customer time-to-value (TTV), integration milestones, and implementation task blockers.',
    version: '1.0.0',
    riskLevel: 'T1',
    allowedTools: ['track_onboarding_milestones', 'alert_stalled_setup'],
    memoryScope: 'ACCOUNT',
    defaultModel: 'gemini-1.5-flash',
    timeoutMs: 20000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 88,
  },
  {
    agentId: 'support-intelligence-agent',
    name: 'Support Intelligence Agent',
    category: 'OPS',
    description: 'Analyzes support ticket severity, escalation risk, recurring bugs, and SLA violations.',
    version: '1.0.0',
    riskLevel: 'T1',
    allowedTools: ['cluster_tickets', 'detect_sla_breach'],
    memoryScope: 'ACCOUNT',
    defaultModel: 'gemini-1.5-flash',
    timeoutMs: 20000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 90,
  },
  {
    agentId: 'crm-hygiene-agent',
    name: 'CRM Data Hygiene Agent',
    category: 'OPS',
    description: 'Detects duplicate accounts/contacts, missing fields, stale deals, and drafts automated merge plans.',
    version: '1.0.0',
    riskLevel: 'T3',
    allowedTools: ['detect_duplicates', 'propose_crm_merge', 'execute_crm_merge'],
    memoryScope: 'ORGANIZATION',
    defaultModel: 'claude-3-5-sonnet',
    timeoutMs: 40000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: true,
    evaluationThreshold: 96,
  },
  {
    agentId: 'data-quality-agent',
    name: 'Data Quality & Drift Agent',
    category: 'OPS',
    description: 'Monitors database schema drift, invalid foreign keys, and anomaly distributions in CRM metrics.',
    version: '1.0.0',
    riskLevel: 'T2',
    allowedTools: ['check_schema_anomalies', 'validate_crm_invariants'],
    memoryScope: 'ORGANIZATION',
    defaultModel: 'gemini-1.5-flash',
    timeoutMs: 25000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 92,
  },
  {
    agentId: 'knowledge-agent',
    name: 'Enterprise Knowledge Agent',
    category: 'KNOWLEDGE',
    description: 'Ingests, parses, normalizes, and extracts entity-relationship structures from enterprise documents.',
    version: '1.0.0',
    riskLevel: 'T1',
    allowedTools: ['parse_document', 'extract_entities', 'index_chunks'],
    memoryScope: 'ORGANIZATION',
    defaultModel: 'gemini-1.5-pro',
    timeoutMs: 45000,
    retryPolicy: { maxRetries: 3, backoffMultiplier: 2.0 },
    approvalRequired: false,
    evaluationThreshold: 90,
  },
  {
    agentId: 'rag-agent',
    name: 'Hybrid RAG Retrieval Agent',
    category: 'KNOWLEDGE',
    description: 'Executes dense vector + sparse keyword search with reranking, ACL enforcement, and context packing.',
    version: '1.0.0',
    riskLevel: 'T1',
    allowedTools: ['hybrid_vector_search', 'rerank_passages', 'pack_context'],
    memoryScope: 'TASK',
    defaultModel: 'gemini-1.5-pro',
    timeoutMs: 20000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 94,
  },
  {
    agentId: 'retrieval-judge',
    name: 'Retrieval Groundedness Judge',
    category: 'KNOWLEDGE',
    description: 'Validates citation provenance, checks hallucination scores, and verifies factual grounding.',
    version: '1.0.0',
    riskLevel: 'T1',
    allowedTools: ['verify_citations', 'score_groundedness'],
    memoryScope: 'TASK',
    defaultModel: 'claude-3-5-sonnet',
    timeoutMs: 25000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 95,
  },
  {
    agentId: 'policy-agent',
    name: 'Policy & Governance Agent',
    category: 'GOVERNANCE',
    description: 'Enforces T0–T5 capability token gating, PII redaction, and Human-in-the-Loop approval requirements.',
    version: '1.0.0',
    riskLevel: 'T3',
    allowedTools: ['evaluate_capability_gate', 'enforce_hitl_approval'],
    memoryScope: 'ORGANIZATION',
    defaultModel: 'claude-3-5-sonnet',
    timeoutMs: 15000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.0 },
    approvalRequired: true,
    evaluationThreshold: 98,
  },
  {
    agentId: 'security-agent',
    name: 'AI Security & Prompt Shield Agent',
    category: 'GOVERNANCE',
    description: 'Screens prompts and tool inputs for direct/indirect prompt injection, jailbreaks, and data leakage.',
    version: '1.0.0',
    riskLevel: 'T4',
    allowedTools: ['scan_adversarial_threats', 'quarantine_agent'],
    memoryScope: 'ORGANIZATION',
    defaultModel: 'gemini-1.5-flash',
    timeoutMs: 10000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.0 },
    approvalRequired: false,
    evaluationThreshold: 99,
  },
  {
    agentId: 'compliance-agent',
    name: 'Compliance & Audit Agent',
    category: 'GOVERNANCE',
    description: 'Validates SOC2 controls, maintains cryptographic evidence hash chains, and handles GDPR requests.',
    version: '1.0.0',
    riskLevel: 'T3',
    allowedTools: ['verify_evidence_chain', 'export_audit_bundle'],
    memoryScope: 'ORGANIZATION',
    defaultModel: 'claude-3-5-sonnet',
    timeoutMs: 30000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: true,
    evaluationThreshold: 98,
  },
  {
    agentId: 'tool-reliability-agent',
    name: 'MCP Tool Reliability Agent',
    category: 'OPS',
    description: 'Monitors MCP server latency, error rates, schema compliance, and triggers circuit breakers.',
    version: '1.0.0',
    riskLevel: 'T2',
    allowedTools: ['probe_mcp_health', 'trip_tool_circuit_breaker'],
    memoryScope: 'ORGANIZATION',
    defaultModel: 'gemini-1.5-flash',
    timeoutMs: 15000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 92,
  },
  {
    agentId: 'cost-optimization-agent',
    name: 'FinOps Cost Optimization Agent',
    category: 'GOVERNANCE',
    description: 'Analyzes model token burn, enforces per-tenant budgets, and optimizes model routing thresholds.',
    version: '1.0.0',
    riskLevel: 'T2',
    allowedTools: ['check_token_budgets', 'recommend_model_switch'],
    memoryScope: 'ORGANIZATION',
    defaultModel: 'gemini-1.5-flash',
    timeoutMs: 15000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 94,
  },
  {
    agentId: 'experiment-agent',
    name: 'Prompt & Model Experiment Agent',
    category: 'HARNESS',
    description: 'Runs A/B evaluation tests across prompt variations and model providers with statistical confidence.',
    version: '1.0.0',
    riskLevel: 'T1',
    allowedTools: ['run_ab_experiment', 'calculate_statistical_significance'],
    memoryScope: 'ORGANIZATION',
    defaultModel: 'gemini-1.5-pro',
    timeoutMs: 60000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 90,
  },
  {
    agentId: 'evaluation-agent',
    name: 'Agent Trajectory Evaluation Agent',
    category: 'HARNESS',
    description: 'Evaluates agent run trajectories against golden benchmarks, adversarial prompts, and regression suites.',
    version: '1.0.0',
    riskLevel: 'T2',
    allowedTools: ['execute_benchmark_suite', 'score_trajectory'],
    memoryScope: 'ORGANIZATION',
    defaultModel: 'claude-3-5-sonnet',
    timeoutMs: 45000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 95,
  },
  {
    agentId: 'harness-judge',
    name: 'Harness Promotion Judge',
    category: 'HARNESS',
    description: 'Autonomous gatekeeper for promoting agent versions from DRAFT to EVALUATING, CANARY, and PRODUCTION.',
    version: '1.0.0',
    riskLevel: 'T3',
    allowedTools: ['evaluate_promotion_criteria', 'promote_agent_version'],
    memoryScope: 'ORGANIZATION',
    defaultModel: 'claude-3-5-sonnet',
    timeoutMs: 30000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: true,
    evaluationThreshold: 98,
  },
  {
    agentId: 'executive-reporting-agent',
    name: 'Executive Reporting Agent',
    category: 'GTM',
    description: 'Compiles weekly and monthly revenue performance reports with graphs and AI-assisted attribution.',
    version: '1.0.0',
    riskLevel: 'T1',
    allowedTools: ['compile_revenue_report', 'export_pdf_briefing'],
    memoryScope: 'ORGANIZATION',
    defaultModel: 'gemini-1.5-pro',
    timeoutMs: 40000,
    retryPolicy: { maxRetries: 2, backoffMultiplier: 1.5 },
    approvalRequired: false,
    evaluationThreshold: 92,
  },
  {
    agentId: 'workflow-recovery-agent',
    name: 'Workflow Self-Healing & Recovery Agent',
    category: 'OPS',
    description: 'Recovers failed workflow steps, executes rollback compensations, and clears dead-letter queues.',
    version: '1.0.0',
    riskLevel: 'T3',
    allowedTools: ['replay_workflow_step', 'execute_compensation_rollback'],
    memoryScope: 'ORGANIZATION',
    defaultModel: 'claude-3-5-sonnet',
    timeoutMs: 30000,
    retryPolicy: { maxRetries: 3, backoffMultiplier: 2.0 },
    approvalRequired: true,
    evaluationThreshold: 96,
  },
];

export class AgentRosterManager {
  private static roster = new Map<string, SpecializedAgentSpec>();

  static {
    for (const agent of SHIVI_38_CORE_AGENTS) {
      this.roster.set(agent.agentId, agent);
    }
  }

  public static getAllAgents(): SpecializedAgentSpec[] {
    return Array.from(this.roster.values());
  }

  public static getAgent(agentId: string): SpecializedAgentSpec | undefined {
    return this.roster.get(agentId);
  }

  public static getAgentsByCategory(category: SpecializedAgentSpec['category']): SpecializedAgentSpec[] {
    return Array.from(this.roster.values()).filter(a => a.category === category);
  }
}
